"""
Auto-generated version information for Hei-DataHub.

DO NOT EDIT THIS FILE DIRECTLY!
This file is generated by scripts/sync_version.py from version.yaml
"""

# Version Components
__version__ = "0.55.5-beta"
__version_info__ = (0, 55, 5, "beta")

# Application Metadata
__app_name__ = "Hei-DataHub"
__license__ = "MIT"
__description__ = "A local-first TUI for managing datasets with consistent metadata"

# Build Information
BUILD_NUMBER = "005505"
RELEASE_DATE = "2025-10-04"
CODENAME = "Fjord"
COMPATIBILITY = "Hei-DataHub v0.55.x (beta)"
RELEASE_NOTES = "Enhanced versioning system with centralized configuration"

# Repository Information
GITHUB_REPO = "0xpix/Hei-DataHub"
GITHUB_URL = f"https://github.com/{GITHUB_REPO}"
ISSUES_URL = f"{GITHUB_URL}/issues"
DOCS_URL = "https://0xpix.github.io/Hei-DataHub"

# Update Check Configuration
UPDATE_CHECK_URL = f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"
UPDATE_CHECK_INTERVAL = 86400  # 24 hours in seconds


def get_version_string(include_build: bool = False) -> str:
    """Get the version string with optional build number."""
    version = __version__
    if include_build:
        version = f"{version} (build {BUILD_NUMBER})"
    return version


def get_version_info() -> dict:
    """Get comprehensive version information as a dictionary."""
    import sys
    return {
        "version": __version__,
        "version_tuple": __version_info__,
        "app_name": __app_name__,
        "build_number": BUILD_NUMBER,
        "release_date": RELEASE_DATE,
        "codename": CODENAME,
        "compatibility": COMPATIBILITY,
        "release_notes": RELEASE_NOTES,
        "python_version": f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
        "python_implementation": sys.implementation.name,
        "github_repo": GITHUB_REPO,
        "github_url": GITHUB_URL,
        "docs_url": DOCS_URL,
    }


def print_version_info(verbose: bool = False) -> None:
    """Print version information to stdout."""
    print(f"{__app_name__} {__version__}")
    if verbose:
        print(f"Build: {BUILD_NUMBER}")
        print(f"Release Date: {RELEASE_DATE}")
        print(f"Codename: {CODENAME}")
        print(f"Compatibility: {COMPATIBILITY}")
        print(f"Repository: {GITHUB_URL}")
        print(f"Documentation: {DOCS_URL}")
        import sys
        print(f"Python: {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro} ({sys.implementation.name})")
